### PR TITLE
Add configuration to support changing namespace behaviors like the current version of etsy's statsd

### PR DESCRIPTION
**Pull request by gmr**
- Add the same options but underscore delimited instead of camelCase, where supported
  - legacy_namespace
  - global_prefix
  - prefix_counter
  - prefix_timer
  - prefix_gauge
- Default to new namespace structure as defined by https://github.com/etsy/statsd/blob/master/docs/namespacing.md
- Minor refactors to minimize code or reduce operations
- Add a few debug checks for print output

### CODE REVIEW

**Comment by gmr** [comment]
I ended up adding an additional changeset that makes logging configurable.

Let met know if you want them split up or if you prefer one vs the other, etc.

**Comment by pandemicsyn** [comment]
Nice! Meant to look at this today but got caught up with $DAYJOB. I'll try to take a look and merge this tomorrow.

**Comment by pandemicsyn** [comment]
I appreciate the pull for the namespacing change (its awesome!).  I'd prefer not to go with the new logging setup though to be honest, I know what I've got in there now is not the best setup but I'm trying to keep it super simple.

**Comment by gmr** [comment]
Would you be open to the logging config change if it worked out of the box with no logging config in the file? ie have sensible built in defaults, but still allow configuration based logging?

**Pull request closed without merging**
